name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-4-dev meson
      - run: meson setup . build
      - run: meson compile -C build
